# Generated by Django 4.2.6 on 2023-11-14 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataKriteria',
            fields=[
                ('kode_kriteria', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nama_kriteria', models.CharField(max_length=255)),
                ('nilai_kriteria', models.FloatField()),
                ('tipe_kriteria', models.CharField(choices=[('B', 'B'), ('C', 'C')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DataKuliner',
            fields=[
                ('id_kuliner', models.AutoField(primary_key=True, serialize=False)),
                ('nama_usaha', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JenisUsaha',
            fields=[
                ('id_usaha', models.AutoField(primary_key=True, serialize=False)),
                ('nama_jenis', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KonversiPenilaian',
            fields=[
                ('id_konversi', models.AutoField(primary_key=True, serialize=False)),
                ('nama_usaha', models.CharField(default='', max_length=255)),
                ('C1', models.IntegerField()),
                ('C2', models.IntegerField()),
                ('C3', models.IntegerField()),
                ('C4', models.IntegerField()),
                ('C5', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DataBobot',
            fields=[
                ('id_bobot', models.AutoField(primary_key=True, serialize=False)),
                ('nama_bobot', models.CharField(max_length=255)),
                ('nilai_bobot', models.FloatField()),
                ('kode_kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabeldatabase.datakriteria')),
            ],
        ),
    ]
